In [ ]:
from google.colab import files

uploaded = files.upload()

Saving student+performance.zip to student+performance.zip

In [ ]:
import zipfile
import os

zip_file = next(iter(uploaded))

with zipfile.ZipFile(zip_file, 'r') as zip_ref:
    zip_ref.extractall("student_performance")

print("Extracted files:")
print(os.listdir("student_performance"))

Extracted files:
['student.zip', '.student.zip_old']

In [ ]:
import os

for root, dirs, files in os.walk("student_performance"):
    for file in files:
        print(os.path.join(root, file))

student_performance/student.zip
student_performance/.student.zip_old

In [ ]:
import zipfile
import os

inner_zip = "student_performance/student.zip"

with zipfile.ZipFile(inner_zip, 'r') as zip_ref:
    zip_ref.extractall("student_data")

print("Dataset files:")
print(os.listdir("student_data"))

Dataset files:
['student-por.csv', 'student-mat.csv', 'student-merge.R', 'student.txt']

In [ ]:
import pandas as pd

df = pd.read_csv("student_data/student-mat.csv", sep=";")

print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

print("\nFirst 5 rows:")
display(df.head())

Shape: (395, 33)

Columns:
['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu', 'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime', 'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery', 'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc', 'Walc', 'health', 'absences', 'G1', 'G2', 'G3']

First 5 rows:

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [ ]:
print("Data types and missing values:")
display(df.info())

print("\nMissing values:")
display(df.isnull().sum())

print("\nNumerical summary:")
display(df.describe())

Data types and missing values:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      395 non-null    object
 1   sex         395 non-null    object
 2   age         395 non-null    int64
 3   address     395 non-null    object
 4   famsize     395 non-null    object
 5   Pstatus     395 non-null    object
 6   Medu        395 non-null    int64
 7   Fedu        395 non-null    int64
 8   Mjob        395 non-null    object
 9   Fjob        395 non-null    object
 10  reason      395 non-null    object
 11  guardian    395 non-null    object
 12  traveltime  395 non-null    int64
 13  studytime   395 non-null    int64
 14  failures    395 non-null    int64
 15  schoolsup   395 non-null    object
 16  famsup      395 non-null    object
 17  paid        395 non-null    object
 18  activities  395 non-null    object
 19  nursery     395 non-null    object
 20  higher      395 non-null    object
 21  internet    395 non-null    object
 22  romantic    395 non-null    object
 23  famrel      395 non-null    int64
 24  freetime    395 non-null    int64
 25  goout       395 non-null    int64
 26  Dalc        395 non-null    int64
 27  Walc        395 non-null    int64
 28  health      395 non-null    int64
 29  absences    395 non-null    int64
 30  G1          395 non-null    int64
 31  G2          395 non-null    int64
 32  G3          395 non-null    int64
dtypes: int64(16), object(17)
memory usage: 102.0+ KB

None

Missing values:

school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64

Numerical summary:

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
count,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000
mean,16.696203,2.749367,2.521519,1.448101,2.035443,0.334177,3.944304,3.235443,3.108861,1.481013,2.291139,3.554430,5.708861,10.908861,10.713924,10.415190
std,1.276043,1.094735,1.088201,0.697505,0.839240,0.743651,0.896659,0.998862,1.113278,0.890741,1.287897,1.390303,8.003096,3.319195,3.761505,4.581443
min,15.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,3.000000,0.000000,0.000000
25%,16.000000,2.000000,2.000000,1.000000,1.000000,0.000000,4.000000,3.000000,2.000000,1.000000,1.000000,3.000000,0.000000,8.000000,9.000000,8.000000
50%,17.000000,3.000000,2.000000,1.000000,2.000000,0.000000,4.000000,3.000000,3.000000,1.000000,2.000000,4.000000,4.000000,11.000000,11.000000,11.000000
75%,18.000000,4.000000,3.000000,2.000000,2.000000,0.000000,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,8.000000,13.000000,13.000000,14.000000
max,22.000000,4.000000,4.000000,4.000000,4.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,75.000000,19.000000,19.000000,20.000000

In [ ]:
import pandas as pd

grade_corr = df[["G1", "G2", "G3"]].corr()

print("Correlation between grades:")
display(grade_corr)

print("\nG3 distribution:")
display(df["G3"].value_counts().sort_index())

Correlation between grades:

          G1        G2        G3
G1  1.000000  0.852118  0.801468
G2  0.852118  1.000000  0.904868
G3  0.801468  0.904868  1.000000

G3 distribution:

G3
0     38
4      1
5      7
6     15
7      9
8     32
9     28
10    56
11    47
12    31
13    31
14    27
15    33
16    16
17     6
18    12
19     5
20     1
Name: count, dtype: int64

In [ ]:
# Target variable
y = df["G3"]

# Input features
X = df.drop(columns=["G3"])

print("X shape:", X.shape)
print("y shape:", y.shape)

print("\nInput features:")
print(X.columns.tolist())

print("\nTarget:")
print(y.name)

X shape: (395, 32)
y shape: (395,)

Input features:
['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu', 'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime', 'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery', 'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc', 'Walc', 'health', 'absences', 'G1', 'G2']

Target:
G3

In [ ]:
numeric_features = X.select_dtypes(include=["int64", "float64"]).columns.tolist()
categorical_features = X.select_dtypes(include=["object"]).columns.tolist()

print("Numerical features:", len(numeric_features))
print(numeric_features)

print("\nCategorical features:", len(categorical_features))
print(categorical_features)

Numerical features: 15
['age', 'Medu', 'Fedu', 'traveltime', 'studytime', 'failures', 'famrel', 'freetime', 'goout', 'Dalc', 'Walc', 'health', 'absences', 'G1', 'G2']

Categorical features: 17
['school', 'sex', 'address', 'famsize', 'Pstatus', 'Mjob', 'Fjob', 'reason', 'guardian', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery', 'higher', 'internet', 'romantic']

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("Training set:")
print("X_train:", X_train.shape)
print("y_train:", y_train.shape)

print("\nTesting set:")
print("X_test:", X_test.shape)
print("y_test:", y_test.shape)

Training set:
X_train: (316, 32)
y_train: (316,)

Testing set:
X_test: (79, 32)
y_test: (79,)

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

preprocessor = ColumnTransformer(
    transformers=[
        ("num", "passthrough", numeric_features),
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features)
    ]
)

print("Preprocessor created successfully.")

Preprocessor created successfully.

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression

linear_model = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("model", LinearRegression())
    ]
)

print("Linear Regression pipeline created successfully.")

Linear Regression pipeline created successfully.

In [ ]:
linear_model.fit(X_train, y_train)

print("Linear Regression model trained successfully.")

Linear Regression model trained successfully.

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

y_pred_linear = linear_model.predict(X_test)

mae_linear = mean_absolute_error(y_test, y_pred_linear)
rmse_linear = np.sqrt(mean_squared_error(y_test, y_pred_linear))
r2_linear = r2_score(y_test, y_pred_linear)

print("Linear Regression Results")
print("-------------------------")
print(f"MAE  : {mae_linear:.4f}")
print(f"RMSE : {rmse_linear:.4f}")
print(f"R²   : {r2_linear:.4f}")

Linear Regression Results
-------------------------
MAE  : 1.6467
RMSE : 2.3784
R²   : 0.7241

In [ ]:
from sklearn.ensemble import RandomForestRegressor

random_forest_model = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("model", RandomForestRegressor(
            n_estimators=300,
            random_state=42,
            n_jobs=-1
        ))
    ]
)

print("Random Forest pipeline created successfully.")

Random Forest pipeline created successfully.

In [ ]:
random_forest_model.fit(X_train, y_train)

print("Random Forest model trained successfully.")

Random Forest model trained successfully.

In [ ]:
y_pred_rf = random_forest_model.predict(X_test)

mae_rf = mean_absolute_error(y_test, y_pred_rf)
rmse_rf = np.sqrt(mean_squared_error(y_test, y_pred_rf))
r2_rf = r2_score(y_test, y_pred_rf)

print("Random Forest Results")
print("---------------------")
print(f"MAE  : {mae_rf:.4f}")
print(f"RMSE : {rmse_rf:.4f}")
print(f"R²   : {r2_rf:.4f}")

Random Forest Results
---------------------
MAE  : 1.1863
RMSE : 2.0023
R²   : 0.8045

In [ ]:
from sklearn.ensemble import HistGradientBoostingRegressor

gradient_boosting_model = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("model", HistGradientBoostingRegressor(
            random_state=42
        ))
    ]
)

print("HistGradientBoosting pipeline created successfully.")

HistGradientBoosting pipeline created successfully.

In [ ]:
gradient_boosting_model.fit(X_train, y_train)

print("HistGradientBoosting model trained successfully.")

HistGradientBoosting model trained successfully.

In [ ]:
y_pred_gb = gradient_boosting_model.predict(X_test)

mae_gb = mean_absolute_error(y_test, y_pred_gb)
rmse_gb = np.sqrt(mean_squared_error(y_test, y_pred_gb))
r2_gb = r2_score(y_test, y_pred_gb)

print("HistGradientBoosting Results")
print("----------------------------")
print(f"MAE  : {mae_gb:.4f}")
print(f"RMSE : {rmse_gb:.4f}")
print(f"R²   : {r2_gb:.4f}")

HistGradientBoosting Results
----------------------------
MAE  : 1.2321
RMSE : 1.9348
R²   : 0.8174

In [ ]:
results = pd.DataFrame({
    "Model": [
        "Linear Regression",
        "Random Forest",
        "HistGradientBoosting"
    ],
    "MAE": [
        mae_linear,
        mae_rf,
        mae_gb
    ],
    "RMSE": [
        rmse_linear,
        rmse_rf,
        rmse_gb
    ],
    "R2": [
        r2_linear,
        r2_rf,
        r2_gb
    ]
})

results = results.sort_values("RMSE").reset_index(drop=True)

display(results)

                  Model       MAE      RMSE        R2
0  HistGradientBoosting  1.232121  1.934810  0.817436
1         Random Forest  1.186287  2.002337  0.804470
2     Linear Regression  1.646666  2.378370  0.724134

In [ ]:
best_model = gradient_boosting_model

print("Selected model: HistGradientBoostingRegressor")
print(f"MAE  : {mae_gb:.4f}")
print(f"RMSE : {rmse_gb:.4f}")
print(f"R²   : {r2_gb:.4f}")

Selected model: HistGradientBoostingRegressor
MAE  : 1.2321
RMSE : 1.9348
R²   : 0.8174

In [ ]:
comparison = pd.DataFrame({
    "Actual_G3": y_test.values,
    "Predicted_G3": y_pred_gb
})

comparison["Error"] = comparison["Actual_G3"] - comparison["Predicted_G3"]

display(comparison.head(15))

    Actual_G3  Predicted_G3     Error
0          10      7.924801  2.075199
1          12     12.246374 -0.246374
2           5      5.673046 -0.673046
3          10      9.897333  0.102667
4           9      9.270553 -0.270553
5          13     11.759070  1.240930
6          18     17.138377  0.861623
7           6      7.720414 -1.720414
8           0      6.659831 -6.659831
9          14     13.494674  0.505326
10         15     14.592085  0.407915
11          7      6.607163  0.392837
12         15     13.170510  1.829490
13         10     11.440521 -1.440521
14         14     14.712076 -0.712076

In [ ]:
import joblib

model_filename = "performance_model.pkl"

joblib.dump(best_model, model_filename)

print(f"Model saved successfully as: {model_filename}")

Model saved successfully as: performance_model.pkl

In [ ]:
import os
import joblib

print("File exists:", os.path.exists("performance_model.pkl"))
print("File size:", os.path.getsize("performance_model.pkl"), "bytes")

loaded_model = joblib.load("performance_model.pkl")

print("Model loaded successfully.")
print("Model type:", type(loaded_model))

File exists: True
File size: 166553 bytes
Model loaded successfully.
Model type: <class 'sklearn.pipeline.Pipeline'>

In [ ]:
loaded_predictions = loaded_model.predict(X_test)

print("First 10 predictions from reloaded model:")
for actual, predicted in zip(y_test.iloc[:10], loaded_predictions[:10]):
    print(f"Actual: {actual:2d}  |  Predicted: {predicted:.2f}")

First 10 predictions from reloaded model:
Actual: 10  |  Predicted: 7.92
Actual: 12  |  Predicted: 12.25
Actual:  5  |  Predicted: 5.67
Actual: 10  |  Predicted: 9.90
Actual:  9  |  Predicted: 9.27
Actual: 13  |  Predicted: 11.76
Actual: 18  |  Predicted: 17.14
Actual:  6  |  Predicted: 7.72
Actual:  0  |  Predicted: 6.66
Actual: 14  |  Predicted: 13.49

In [ ]:
mae_loaded = mean_absolute_error(y_test, loaded_predictions)
rmse_loaded = np.sqrt(mean_squared_error(y_test, loaded_predictions))
r2_loaded = r2_score(y_test, loaded_predictions)

print("Reloaded Model Results")
print("----------------------")
print(f"MAE  : {mae_loaded:.4f}")
print(f"RMSE : {rmse_loaded:.4f}")
print(f"R²   : {r2_loaded:.4f}")

Reloaded Model Results
----------------------
MAE  : 1.2321
RMSE : 1.9348
R²   : 0.8174

In [ ]:
new_student = pd.DataFrame([{
    "school": "GP",
    "sex": "F",
    "age": 17,
    "address": "U",
    "famsize": "GT3",
    "Pstatus": "T",
    "Medu": 3,
    "Fedu": 3,
    "Mjob": "teacher",
    "Fjob": "other",
    "reason": "course",
    "guardian": "mother",
    "traveltime": 1,
    "studytime": 2,
    "failures": 0,
    "schoolsup": "no",
    "famsup": "yes",
    "paid": "no",
    "activities": "yes",
    "nursery": "yes",
    "higher": "yes",
    "internet": "yes",
    "romantic": "no",
    "famrel": 4,
    "freetime": 3,
    "goout": 3,
    "Dalc": 1,
    "Walc": 1,
    "health": 4,
    "absences": 4,
    "G1": 12,
    "G2": 13
}])

predicted_g3 = loaded_model.predict(new_student)[0]

print(f"Predicted final grade (G3): {predicted_g3:.2f}")

Predicted final grade (G3): 13.70