In [ ]:
from google.colab import files

uploaded = files.upload()

Saving student+performance.zip to student+performance.zip

In [ ]:
import zipfile
import os

zip_file = next(iter(uploaded))

with zipfile.ZipFile(zip_file, "r") as zip_ref:
    zip_ref.extractall("student_performance")

print("Extracted files:")
print(os.listdir("student_performance"))

Extracted files:
['student.zip', '.student.zip_old']

In [ ]:
import zipfile
import os

inner_zip = "student_performance/student.zip"

with zipfile.ZipFile(inner_zip, "r") as zip_ref:
    zip_ref.extractall("student_data")

print("Dataset files:")
print(os.listdir("student_data"))

Dataset files:
['student-por.csv', 'student-mat.csv', 'student-merge.R', 'student.txt']

In [ ]:
import pandas as pd

df = pd.read_csv("student_data/student-mat.csv", sep=";")

print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

print("\nFirst 5 rows:")
display(df.head())

Shape: (395, 33)

Columns:
['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu', 'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime', 'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery', 'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc', 'Walc', 'health', 'absences', 'G1', 'G2', 'G3']

First 5 rows:

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [ ]:
academic_columns = [
    "absences",
    "G1",
    "G2",
    "G3",
    "failures",
    "studytime"
]

print("Academic indicator summary:")
display(df[academic_columns].describe())

print("\nUnique values:")
for column in academic_columns:
    print(f"\n{column}:")
    print(sorted(df[column].unique()))

Academic indicator summary:

         absences          G1          G2          G3    failures   studytime
count  395.000000  395.000000  395.000000  395.000000  395.000000  395.000000
mean     5.708861   10.908861   10.713924   10.415190    0.334177    2.035443
std      8.003096    3.319195    3.761505    4.581443    0.743651    0.839240
min      0.000000    3.000000    0.000000    0.000000    0.000000    1.000000
25%      0.000000    8.000000    9.000000    8.000000    0.000000    1.000000
50%      4.000000   11.000000   11.000000   11.000000    0.000000    2.000000
75%      8.000000   13.000000   13.000000   14.000000    0.000000    2.000000
max     75.000000   19.000000   19.000000   20.000000    3.000000    4.000000

Unique values:

absences:
[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(24), np.int64(25), np.int64(26), np.int64(28), np.int64(30), np.int64(38), np.int64(40), np.int64(54), np.int64(56), np.int64(75)]

G1:
[np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19)]

G2:
[np.int64(0), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19)]

G3:
[np.int64(0), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20)]

failures:
[np.int64(0), np.int64(1), np.int64(2), np.int64(3)]

studytime:
[np.int64(1), np.int64(2), np.int64(3), np.int64(4)]

In [ ]:
df["performance_trend"] = df["G2"] - df["G1"]

print("Performance trend summary:")
display(df["performance_trend"].describe())

print("\nTrend distribution:")
print(
    df["performance_trend"]
    .apply(
        lambda x: "Improving" if x > 0
        else "Stable" if x == 0
        else "Declining"
    )
    .value_counts()
)

Performance trend summary:

count    395.000000
mean      -0.194937
std        1.971877
min      -12.000000
25%       -1.000000
50%        0.000000
75%        1.000000
max        4.000000
Name: performance_trend, dtype: float64

Trend distribution:
performance_trend
Declining    150
Improving    128
Stable       117
Name: count, dtype: int64

In [ ]:
def absence_risk(absences):
    if absences <= 4:
        return 0
    elif absences <= 9:
        return 1
    else:
        return 2

df["absence_risk"] = df["absences"].apply(absence_risk)

print("Absence risk distribution:")
print(
    df["absence_risk"]
    .value_counts()
    .sort_index()
    .rename({
        0: "LOW",
        1: "MEDIUM",
        2: "HIGH"
    })
)

Absence risk distribution:
absence_risk
LOW       244
MEDIUM     68
HIGH       83
Name: count, dtype: int64

In [ ]:
def performance_risk(g2):
    if g2 >= 12:
        return 0
    elif g2 >= 10:
        return 1
    else:
        return 2

df["performance_risk"] = df["G2"].apply(performance_risk)

print("Performance risk distribution:")
print(
    df["performance_risk"]
    .value_counts()
    .sort_index()
    .rename({
        0: "LOW",
        1: "MEDIUM",
        2: "HIGH"
    })
)

Performance risk distribution:
performance_risk
LOW       168
MEDIUM     81
HIGH      146
Name: count, dtype: int64

In [ ]:
def trend_risk(trend):
    if trend > 0:
        return 0
    elif trend == 0:
        return 1
    else:
        return 2

df["trend_risk"] = df["performance_trend"].apply(trend_risk)

print("Trend risk distribution:")
print(
    df["trend_risk"]
    .value_counts()
    .sort_index()
    .rename({
        0: "LOW",
        1: "MEDIUM",
        2: "HIGH"
    })
)

Trend risk distribution:
trend_risk
LOW       128
MEDIUM    117
HIGH      150
Name: count, dtype: int64

In [ ]:
def failure_risk(failures):
    if failures == 0:
        return 0
    elif failures == 1:
        return 1
    else:
        return 2

df["failure_risk"] = df["failures"].apply(failure_risk)

print("Previous failure risk distribution:")
print(
    df["failure_risk"]
    .value_counts()
    .sort_index()
    .rename({
        0: "LOW",
        1: "MEDIUM",
        2: "HIGH"
    })
)

Previous failure risk distribution:
failure_risk
LOW       312
MEDIUM     50
HIGH       33
Name: count, dtype: int64

In [ ]:
def studytime_risk(studytime):
    if studytime >= 3:
        return 0
    elif studytime == 2:
        return 1
    else:
        return 2

df["studytime_risk"] = df["studytime"].apply(studytime_risk)

print("Study-time risk distribution:")
print(
    df["studytime_risk"]
    .value_counts()
    .sort_index()
    .rename({
        0: "LOW",
        1: "MEDIUM",
        2: "HIGH"
    })
)

Study-time risk distribution:
studytime_risk
LOW        92
MEDIUM    198
HIGH      105
Name: count, dtype: int64

In [ ]:
df["risk_score"] = (
    (df["absence_risk"] / 2) * 25 +
    (df["performance_risk"] / 2) * 30 +
    (df["trend_risk"] / 2) * 20 +
    (df["failure_risk"] / 2) * 15 +
    (df["studytime_risk"] / 2) * 10
)

print("Risk score summary:")
display(df["risk_score"].describe())

print("\nFirst 10 risk scores:")
display(
    df[
        [
            "absences",
            "G1",
            "G2",
            "failures",
            "studytime",
            "performance_trend",
            "risk_score"
        ]
    ].head(10)
)

Risk score summary:

count    395.000000
mean      39.493671
std       23.660095
min        0.000000
25%       20.000000
50%       35.000000
75%       55.000000
max      100.000000
Name: risk_score, dtype: float64

First 10 risk scores:

   absences  G1  G2  failures  studytime  performance_trend  risk_score
0         6   5   6         0          2                  1        47.5
1         4   5   5         0          2                  0        45.0
2        10   7   8         3          2                  1        75.0
3         2  15  14         0          3                 -1        20.0
4         4   6  10         0          2                  4        20.0
5        10  15  15         0          2                  0        40.0
6         0  12  12         0          2                  0        15.0
7         6   6   5         0          2                 -1        67.5
8         0  16  18         0          2                  2         5.0
9         0  14  15         0          2                  1         5.0

In [ ]:
def risk_level(score):
    if score <= 30:
        return "LOW"
    elif score <= 60:
        return "MEDIUM"
    else:
        return "HIGH"


df["risk_level"] = df["risk_score"].apply(risk_level)

print("Risk level distribution:")
print(df["risk_level"].value_counts())

print("\nRisk level percentages:")
print(
    df["risk_level"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

Risk level distribution:
risk_level
LOW       165
MEDIUM    151
HIGH       79
Name: count, dtype: int64

Risk level percentages:
risk_level
LOW       41.77
MEDIUM    38.23
HIGH      20.00
Name: proportion, dtype: float64

In [ ]:
high_risk_students = df[
    df["risk_level"] == "HIGH"
][
    [
        "absences",
        "G1",
        "G2",
        "failures",
        "studytime",
        "performance_trend",
        "absence_risk",
        "performance_risk",
        "trend_risk",
        "failure_risk",
        "studytime_risk",
        "risk_score",
        "risk_level"
    ]
].sort_values(
    "risk_score",
    ascending=False
)

print("High-risk students:", len(high_risk_students))

display(high_risk_students.head(20))

High-risk students: 79

,absences,G1,G2,failures,studytime,performance_trend,absence_risk,performance_risk,trend_risk,failure_risk,studytime_risk,risk_score,risk_level
18,16,6,5,3,1,-1,2,2,2,2,2,100.0,HIGH
281,19,11,9,1,1,-2,2,2,2,1,2,92.5,HIGH
384,14,6,5,1,1,-1,2,2,2,1,2,92.5,HIGH
157,6,9,8,3,1,-1,1,2,2,2,2,87.5,HIGH
118,20,9,7,1,2,-2,2,2,2,1,1,87.5,HIGH
278,15,9,8,1,2,-1,2,2,2,1,1,87.5,HIGH
225,16,9,8,1,2,-1,2,2,2,1,1,87.5,HIGH
178,10,10,8,0,1,-2,2,2,2,0,2,85.0,HIGH
203,18,7,6,0,1,-1,2,2,2,0,2,85.0,HIGH
216,22,6,6,2,2,0,2,2,1,2,1,85.0,HIGH
270,15,9,9,2,2,0,2,2,1,2,1,85.0,HIGH
373,14,6,5,0,1,-1,2,2,2,0,2,85.0,HIGH
390,11,9,9,2,2,0,2,2,1,2,1,85.0,HIGH
350,8,8,7,3,2,-1,1,2,2,2,1,82.5,HIGH
205,28,10,9,1,3,-1,2,2,2,1,0,82.5,HIGH
232,14,11,9,0,2,-2,2,2,2,0,1,80.0,HIGH
247,16,6,8,3,1,2,2,2,0,2,2,80.0,HIGH
234,18,9,7,0,2,-2,2,2,2,0,1,80.0,HIGH
276,75,10,9,0,2,-1,2,2,2,0,1,80.0,HIGH
352,7,8,7,1,1,-1,1,2,2,1,2,80.0,HIGH

In [ ]:
def calculate_risk(
    absences,
    g1,
    g2,
    failures,
    studytime
):
    # 1. Absence risk
    if absences <= 4:
        absence_risk = 0
    elif absences <= 9:
        absence_risk = 1
    else:
        absence_risk = 2

    # 2. Current performance risk
    if g2 >= 12:
        performance_risk = 0
    elif g2 >= 10:
        performance_risk = 1
    else:
        performance_risk = 2

    # 3. Performance trend
    performance_trend = g2 - g1

    if performance_trend > 0:
        trend_risk = 0
    elif performance_trend == 0:
        trend_risk = 1
    else:
        trend_risk = 2

    # 4. Previous failure risk
    if failures == 0:
        failure_risk = 0
    elif failures == 1:
        failure_risk = 1
    else:
        failure_risk = 2

    # 5. Study-time risk
    if studytime >= 3:
        studytime_risk = 0
    elif studytime == 2:
        studytime_risk = 1
    else:
        studytime_risk = 2

    # Weighted risk score: 0–100
    risk_score = (
        (absence_risk / 2) * 25 +
        (performance_risk / 2) * 30 +
        (trend_risk / 2) * 20 +
        (failure_risk / 2) * 15 +
        (studytime_risk / 2) * 10
    )

    # Risk level
    if risk_score <= 30:
        risk_level = "LOW"
    elif risk_score <= 60:
        risk_level = "MEDIUM"
    else:
        risk_level = "HIGH"

    return {
        "risk_score": risk_score,
        "risk_level": risk_level,
        "absence_risk": absence_risk,
        "performance_risk": performance_risk,
        "trend_risk": trend_risk,
        "failure_risk": failure_risk,
        "studytime_risk": studytime_risk
    }


print("Risk engine function created successfully.")

Risk engine function created successfully.

In [ ]:
student = df.iloc[0]

risk_result = calculate_risk(
    absences=student["absences"],
    g1=student["G1"],
    g2=student["G2"],
    failures=student["failures"],
    studytime=student["studytime"]
)

print("Student data:")
print(f"Absences   : {student['absences']}")
print(f"G1         : {student['G1']}")
print(f"G2         : {student['G2']}")
print(f"Failures   : {student['failures']}")
print(f"Study time : {student['studytime']}")

print("\nRisk Engine Result:")
print(f"Risk Score : {risk_result['risk_score']:.2f}")
print(f"Risk Level : {risk_result['risk_level']}")

print("\nOriginal DataFrame Result:")
print(f"Risk Score : {student['risk_score']:.2f}")
print(f"Risk Level : {student['risk_level']}")

Student data:
Absences   : 6
G1         : 5
G2         : 6
Failures   : 0
Study time : 2

Risk Engine Result:
Risk Score : 47.50
Risk Level : MEDIUM

Original DataFrame Result:
Risk Score : 47.50
Risk Level : MEDIUM

In [ ]:
new_student = {
    "absences": 18,
    "g1": 9,
    "g2": 7,
    "failures": 2,
    "studytime": 1
}

risk_result = calculate_risk(
    absences=new_student["absences"],
    g1=new_student["g1"],
    g2=new_student["g2"],
    failures=new_student["failures"],
    studytime=new_student["studytime"]
)

print("New Student Risk Assessment")
print("----------------------------")
print(f"Absences       : {new_student['absences']}")
print(f"G1             : {new_student['g1']}")
print(f"G2             : {new_student['g2']}")
print(f"Previous Failures: {new_student['failures']}")
print(f"Study Time     : {new_student['studytime']}")

print("\nRisk Result")
print("-----------")
print(f"Risk Score : {risk_result['risk_score']:.2f}/100")
print(f"Risk Level : {risk_result['risk_level']}")

New Student Risk Assessment
----------------------------
Absences       : 18
G1             : 9
G2             : 7
Previous Failures: 2
Study Time     : 1

Risk Result
-----------
Risk Score : 100.00/100
Risk Level : HIGH

In [ ]:
def get_risk_indicators(
    absences,
    g1,
    g2,
    failures,
    studytime
):
    indicators = []

    # Attendance / absence
    if absences >= 10:
        indicators.append("High Absence")
    elif absences >= 5:
        indicators.append("Moderate Absence")

    # Current performance
    if g2 < 10:
        indicators.append("Low Current Performance")
    elif g2 < 12:
        indicators.append("Moderate Current Performance")

    # Performance trend
    trend = g2 - g1

    if trend < 0:
        indicators.append("Declining Performance")
    elif trend == 0:
        indicators.append("Stable Performance")

    # Previous failures
    if failures >= 2:
        indicators.append("Multiple Previous Failures")
    elif failures == 1:
        indicators.append("Previous Failure")

    # Study time
    if studytime == 1:
        indicators.append("Low Study Time")
    elif studytime == 2:
        indicators.append("Moderate Study Time")

    return indicators


indicators = get_risk_indicators(
    absences=new_student["absences"],
    g1=new_student["g1"],
    g2=new_student["g2"],
    failures=new_student["failures"],
    studytime=new_student["studytime"]
)

print("Risk Indicators:")
for indicator in indicators:
    print("-", indicator)

Risk Indicators:
- High Absence
- Low Current Performance
- Declining Performance
- Multiple Previous Failures
- Low Study Time

In [ ]:
def assess_student_risk(
    absences,
    g1,
    g2,
    failures,
    studytime
):
    # Calculate score and risk level
    risk_result = calculate_risk(
        absences=absences,
        g1=g1,
        g2=g2,
        failures=failures,
        studytime=studytime
    )

    # Generate actionable indicators
    indicators = get_risk_indicators(
        absences=absences,
        g1=g1,
        g2=g2,
        failures=failures,
        studytime=studytime
    )

    return {
        "risk_score": round(risk_result["risk_score"], 2),
        "risk_level": risk_result["risk_level"],
        "risk_indicators": indicators
    }


print("Final risk assessment function created successfully.")

Final risk assessment function created successfully.

In [ ]:
final_assessment = assess_student_risk(
    absences=18,
    g1=9,
    g2=7,
    failures=2,
    studytime=1
)

print("Final Student Risk Assessment")
print("-----------------------------")
print(f"Risk Score : {final_assessment['risk_score']}/100")
print(f"Risk Level : {final_assessment['risk_level']}")

print("\nRisk Indicators:")
for indicator in final_assessment["risk_indicators"]:
    print(f"- {indicator}")

Final Student Risk Assessment
-----------------------------
Risk Score : 100.0/100
Risk Level : HIGH

Risk Indicators:
- High Absence
- Low Current Performance
- Declining Performance
- Multiple Previous Failures
- Low Study Time

In [ ]:
risk_results = df.apply(
    lambda row: assess_student_risk(
        absences=row["absences"],
        g1=row["G1"],
        g2=row["G2"],
        failures=row["failures"],
        studytime=row["studytime"]
    ),
    axis=1
)

risk_results_df = pd.DataFrame(risk_results.tolist())

print("Risk assessment completed for all students.")
print("Number of students:", len(risk_results_df))

print("\nRisk level distribution:")
print(risk_results_df["risk_level"].value_counts())

print("\nRisk score summary:")
display(risk_results_df["risk_score"].describe())

Risk assessment completed for all students.
Number of students: 395

Risk level distribution:
risk_level
LOW       165
MEDIUM    151
HIGH       79
Name: count, dtype: int64

Risk score summary:

count    395.000000
mean      39.493671
std       23.660095
min        0.000000
25%       20.000000
50%       35.000000
75%       55.000000
max      100.000000
Name: risk_score, dtype: float64

In [ ]:
risk_dataset = df.copy()

risk_dataset["risk_score"] = risk_results_df["risk_score"]
risk_dataset["risk_level"] = risk_results_df["risk_level"]
risk_dataset["risk_indicators"] = risk_results_df["risk_indicators"]

print("Final risk dataset shape:", risk_dataset.shape)

print("\nRisk dataset columns:")
print(risk_dataset.columns.tolist())

print("\nSample risk assessments:")
display(
    risk_dataset[
        [
            "absences",
            "G1",
            "G2",
            "failures",
            "studytime",
            "performance_trend",
            "risk_score",
            "risk_level",
            "risk_indicators"
        ]
    ].head(10)
)

Final risk dataset shape: (395, 42)

Risk dataset columns:
['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu', 'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime', 'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery', 'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc', 'Walc', 'health', 'absences', 'G1', 'G2', 'G3', 'performance_trend', 'absence_risk', 'performance_risk', 'trend_risk', 'failure_risk', 'studytime_risk', 'risk_score', 'risk_level', 'risk_indicators']

Sample risk assessments:

,absences,G1,G2,failures,studytime,performance_trend,risk_score,risk_level,risk_indicators
0,6,5,6,0,2,1,47.5,MEDIUM,"[Moderate Absence, Low Current Performance, Mo..."
1,4,5,5,0,2,0,45.0,MEDIUM,"[Low Current Performance, Stable Performance, ..."
2,10,7,8,3,2,1,75.0,HIGH,"[High Absence, Low Current Performance, Multip..."
3,2,15,14,0,3,-1,20.0,LOW,[Declining Performance]
4,4,6,10,0,2,4,20.0,LOW,"[Moderate Current Performance, Moderate Study ..."
5,10,15,15,0,2,0,40.0,MEDIUM,"[High Absence, Stable Performance, Moderate St..."
6,0,12,12,0,2,0,15.0,LOW,"[Stable Performance, Moderate Study Time]"
7,6,6,5,0,2,-1,67.5,HIGH,"[Moderate Absence, Low Current Performance, De..."
8,0,16,18,0,2,2,5.0,LOW,[Moderate Study Time]
9,0,14,15,0,2,1,5.0,LOW,[Moderate Study Time]

In [ ]:
student_base = {
    "absences": 8,
    "g1": 10,
    "g2": 9,
    "failures": 1,
    "studytime": 2
}

risk_a = assess_student_risk(**student_base)

# G3 is intentionally changed, but it is NOT passed to the risk engine.
student_with_different_g3 = {
    **student_base,
    "g3": 20
}

risk_b = assess_student_risk(
    absences=student_with_different_g3["absences"],
    g1=student_with_different_g3["g1"],
    g2=student_with_different_g3["g2"],
    failures=student_with_different_g3["failures"],
    studytime=student_with_different_g3["studytime"]
)

print("Risk with G3 = original/unknown:")
print(risk_a)

print("\nRisk with G3 = 20:")
print(risk_b)

print("\nRisk results identical:",
      risk_a == risk_b)

Risk with G3 = original/unknown:
{'risk_score': 75.0, 'risk_level': 'HIGH', 'risk_indicators': ['Moderate Absence', 'Low Current Performance', 'Declining Performance', 'Previous Failure', 'Moderate Study Time']}

Risk with G3 = 20:
{'risk_score': 75.0, 'risk_level': 'HIGH', 'risk_indicators': ['Moderate Absence', 'Low Current Performance', 'Declining Performance', 'Previous Failure', 'Moderate Study Time']}

Risk results identical: True

In [ ]:
risk_config = {
    "weights": {
        "absence": 25,
        "performance": 30,
        "trend": 20,
        "failure": 15,
        "studytime": 10
    },
    "thresholds": {
        "risk_level": {
            "low_max": 30,
            "medium_max": 60
        },
        "absence": {
            "low_max": 4,
            "medium_max": 9
        },
        "performance": {
            "low_min": 12,
            "medium_min": 10
        },
        "failures": {
            "low": 0,
            "medium": 1,
            "high_min": 2
        },
        "studytime": {
            "high": 1,
            "medium": 2,
            "low_min": 3
        }
    }
}

print("Risk engine configuration:")
print(risk_config)

Risk engine configuration:
{'weights': {'absence': 25, 'performance': 30, 'trend': 20, 'failure': 15, 'studytime': 10}, 'thresholds': {'risk_level': {'low_max': 30, 'medium_max': 60}, 'absence': {'low_max': 4, 'medium_max': 9}, 'performance': {'low_min': 12, 'medium_min': 10}, 'failures': {'low': 0, 'medium': 1, 'high_min': 2}, 'studytime': {'high': 1, 'medium': 2, 'low_min': 3}}}

In [ ]:
test_cases = [
    {
        "name": "Low Risk Student",
        "absences": 0,
        "g1": 15,
        "g2": 16,
        "failures": 0,
        "studytime": 4
    },
    {
        "name": "Medium Risk Student",
        "absences": 5,
        "g1": 11,
        "g2": 10,
        "failures": 1,
        "studytime": 2
    },
    {
        "name": "High Risk Student",
        "absences": 20,
        "g1": 8,
        "g2": 6,
        "failures": 2,
        "studytime": 1
    }
]

for student in test_cases:
    result = assess_student_risk(
        absences=student["absences"],
        g1=student["g1"],
        g2=student["g2"],
        failures=student["failures"],
        studytime=student["studytime"]
    )

    print(student["name"])
    print(f"  Risk Score : {result['risk_score']}/100")
    print(f"  Risk Level : {result['risk_level']}")
    print(f"  Indicators : {result['risk_indicators']}")
    print()

Low Risk Student
  Risk Score : 0.0/100
  Risk Level : LOW
  Indicators : []

Medium Risk Student
  Risk Score : 60.0/100
  Risk Level : MEDIUM
  Indicators : ['Moderate Absence', 'Moderate Current Performance', 'Declining Performance', 'Previous Failure', 'Moderate Study Time']

High Risk Student
  Risk Score : 100.0/100
  Risk Level : HIGH
  Indicators : ['High Absence', 'Low Current Performance', 'Declining Performance', 'Multiple Previous Failures', 'Low Study Time']

In [ ]:
import json

config_filename = "risk_engine_config.json"

with open(config_filename, "w") as f:
    json.dump(risk_config, f, indent=4)

print(f"Risk configuration saved successfully as: {config_filename}")

Risk configuration saved successfully as: risk_engine_config.json

In [ ]:
with open("risk_engine_config.json", "r") as f:
    loaded_risk_config = json.load(f)

print("Configuration loaded successfully.")
print("\nLoaded configuration:")
print(loaded_risk_config)

print("\nConfiguration matches original:",
      loaded_risk_config == risk_config)

Configuration loaded successfully.

Loaded configuration:
{'weights': {'absence': 25, 'performance': 30, 'trend': 20, 'failure': 15, 'studytime': 10}, 'thresholds': {'risk_level': {'low_max': 30, 'medium_max': 60}, 'absence': {'low_max': 4, 'medium_max': 9}, 'performance': {'low_min': 12, 'medium_min': 10}, 'failures': {'low': 0, 'medium': 1, 'high_min': 2}, 'studytime': {'high': 1, 'medium': 2, 'low_min': 3}}}

Configuration matches original: True

In [ ]:
from google.colab import files

files.download("risk_engine_config.json")